version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pedido_postgres
    environment:
      POSTGRES_DB: pedido_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - pedido_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: pedido_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pedido_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - pedido_net

networks:
  pedido_net:

volumes:
  postgres_data:
